name: move_and_draw
description: "A fitness app encouraging to take sports by making them a piece or art"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_sign_in: 7.2.0
  flutter_dotenv: ^6.0.0
  flutter_colorpicker: 1.1.0
  http: ^1.6.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.production

flutter_launcher_icons:
  android: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#F5F5F5"
  adaptive_icon_foreground: "assets/app_icon.png"
